<a href="https://colab.research.google.com/github/Ilukka07I/Analise-lunar/blob/Analise-Agencias/Analise_Agencias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

\

# Git Hub

In [1]:
!git clone https://github.com/Ilukka07I/Analise-lunar.git

Cloning into 'Analise-lunar'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 11.13 KiB | 5.56 MiB/s, done.

# Bliblioteca

In [2]:
import pandas as pd

# Codigo Analise

In [6]:
df_lua = pd.read_csv('/content/Analise-lunar/Moonlanding.csv')

display(df_lua)

,Mission,Spacecraft,Launch Date,Carrier Rocket,Operator,Mission Type,Outcome,Additional Information
0,Pioneer 0 (Able I),Pioneer 0,17-Aug-58,Thor DM-18 Able I,United States USAF,Orbiter,Launch failure,First attempted launch beyond Earth orbit; fai...
1,Luna E-1 No.1,Luna E-1 No.1,23-Sep-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; rocket disintegrated due to e...
2,Pioneer 1 (Able II),Pioneer 1,11-Oct-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
3,Luna E-1 No.2,Luna E-1 No.2,11-Oct-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; carrier rocket exploded due t...
4,Pioneer 2 (Able III),Pioneer 2,08-Nov-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
...,...,...,...,...,...,...,...,...
161,Peregrine Mission One,Peregrine,08-Jan-24,Vulcan Centaur VC2,Astrobotic Technology,Lander,Spacecraft failure,Part of CLPS. Peregrine lander's reaction thru...
162,Peregrine Mission One,Colmena ? 5,08-Jan-24,Vulcan Centaur VC2,UNAM,Rovers,Precluded,Part of CLPS. Peregrine lander's reaction thru...
163,Peregrine Mission One,Iris,08-Jan-24,Vulcan Centaur VC2,CMU,Rover,Precluded,Part of CLPS. Peregrine lander's reaction thru...
164,IM-1,Nova-C Odysseus,14-Feb-24,Falcon 9 B5,Intuitive Machines,Lander,Operational,First Nova-C mission. Payloads successfully de...
165,IM-1,EagleCam,14-Feb-24,Falcon 9 B5,ERAU,Deployable camera (semi hard lander),Awaiting Deployment,First Nova-C mission. Payloads successfully de...

In [12]:
# Quantidade de Missões por cada agencia / Operador Espacial

display(df_lua['Operator'].value_counts())

Operator
United States NASA                   61
Soviet Union Lavochkin               39
Soviet Union OKB-1                   15
China CNSA                           15
Japan JAXA                            5
India ISRO                            4
Japan ISAS                            3
European Union ESA                    2
Tomy / JAXA / Doshisha University     2
United States Hughes                  1
United States USAF/NASA               1
Japan United States ISAS/NASA         1
United States USAF                    1
Luxembourg LuxSpace                   1
Israel SpaceIL                        1
Italy ASI                             1
South Korea KARI                      1
United States Fluid & Reason          1
Japan ispace                          1
Japan Tomy/JAXA/Dodai                 1
United States Lockheed Martin         1
UAE UAESA/MBRSC                       1
Russia Roscosmos                      1
JAXA                                  1
Astrobotic Technology                 1
UNAM                                  1
CMU                                   1
Intuitive Machines                    1
ERAU                                  1
Name: count, dtype: int64

In [14]:
display(df_lua['Operator'].value_counts(normalize=True)*100)

Operator
United States NASA                   36.746988
Soviet Union Lavochkin               23.493976
Soviet Union OKB-1                    9.036145
China CNSA                            9.036145
Japan JAXA                            3.012048
India ISRO                            2.409639
Japan ISAS                            1.807229
European Union ESA                    1.204819
Tomy / JAXA / Doshisha University     1.204819
United States Hughes                  0.602410
United States USAF/NASA               0.602410
Japan United States ISAS/NASA         0.602410
United States USAF                    0.602410
Luxembourg LuxSpace                   0.602410
Israel SpaceIL                        0.602410
Italy ASI                             0.602410
South Korea KARI                      0.602410
United States Fluid & Reason          0.602410
Japan ispace                          0.602410
Japan Tomy/JAXA/Dodai                 0.602410
United States Lockheed Martin         0.602410
UAE UAESA/MBRSC                       0.602410
Russia Roscosmos                      0.602410
JAXA                                  0.602410
Astrobotic Technology                 0.602410
UNAM                                  0.602410
CMU                                   0.602410
Intuitive Machines                    0.602410
ERAU                                  0.602410
Name: proportion, dtype: float64